CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_ZEPHYRDB=y
CONFIG_ZDB_KV=n
CONFIG_ZDB_TS=y
CONFIG_ZDB_TS_BACKEND_FCB=y
CONFIG_ZDB_STATS=y

CONFIG_FCB=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_CRC=y

# Optional tuning for FCB backend
CONFIG_ZDB_TS_FCB_FLASH_AREA_ID=0
CONFIG_ZDB_TS_FCB_SECTOR_COUNT=4
