CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_HEAP_MEM_POOL_SIZE=4096

# ZephyrDB
CONFIG_ZEPHYRDB=y
CONFIG_ZDB_KV=n
CONFIG_ZDB_STATS=y

# Stage 2 bootstrap path
CONFIG_ZDB_FLATBUFFERS=y

# FlatCC runtime
CONFIG_FLATCC=y
CONFIG_FLATCC_ALLOC_ZEPHYR=y
CONFIG_FLATCC_RUNTIME_JSON=n
CONFIG_FLATCC_RUNTIME_REFMAP=y

# Required by ZDB_TS dependency chain
CONFIG_FILE_SYSTEM=y
